### ISSUE TITLE
Link is not available

### ISSUE THREAD

**Issue by andhana** [yogeshk4/FaceAttend#1]
Hello @yogi1997 
Link for the retrained_labels.txt and retrainded_graph.pb is not available, is there another link to download it?

**Comment by yogesh-kamat** [comment]
Yes. I have included those files now.
https://github.com/yogi1997/Face-recognition-based-attendance-system/tree/master/teachers_site/tf_files

**Comment by yogesh-kamat** [comment]
You can also see the project working in detail here 
https://www.youtube.com/watch?v=0ADsRSF_MHw&t=9s
